name: AirdropChecker
options:
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.0"

targets:
  AirdropChecker:
    type: application
    platform: iOS
    sources:
      - path: AirdropChecker
        excludes:
          - "**/*.plist"
    info:
      path: AirdropChecker/Info.plist
    configFiles:
      Debug: Config/Debug.xcconfig
      Release: Config/Release.xcconfig
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO

  AirdropCheckerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AirdropCheckerTests
    dependencies:
      - target: AirdropChecker
    configFiles:
      Debug: Config/Tests.xcconfig
      Release: Config/Tests.xcconfig
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

schemes:
  AirdropChecker:
    build:
      targets:
        AirdropChecker: all
        AirdropCheckerTests: [test]
    test:
      targets:
        - AirdropCheckerTests
    run:
      config: Debug
    archive:
      config: Release
